# Generated by Django 5.2.9 on 2026-01-03 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_post_location_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='匹配分数')),
                ('method', models.CharField(default='tfidf', max_length=50, verbose_name='匹配方法')),
                ('rerank_confidence', models.FloatField(blank=True, null=True, verbose_name='LLM置信度')),
                ('rerank_reason', models.TextField(blank=True, verbose_name='匹配理由')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('accepted', '已接受'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('found_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='MyApp.post', verbose_name='招领帖')),
                ('lost_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='MyApp.post', verbose_name='寻物帖')),
            ],
            options={
                'verbose_name': '候选匹配',
                'verbose_name_plural': '候选匹配',
                'unique_together': {('lost_post', 'found_post')},
            },
        ),
        migrations.CreateModel(
            name='ExtractionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100, verbose_name='物品名称')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='颜色')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('features', models.TextField(blank=True, verbose_name='特征描述')),
                ('location_detail', models.CharField(blank=True, max_length=200, verbose_name='详细位置')),
                ('time_info', models.CharField(blank=True, max_length=100, verbose_name='时间信息')),
                ('raw_json', models.JSONField(default=dict, verbose_name='原始JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyApp.post', verbose_name='关联帖子')),
            ],
            options={
                'verbose_name': '实体抽取缓存',
                'verbose_name_plural': '实体抽取缓存',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.candidatematch', verbose_name='关联匹配')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
            },
        ),
    ]
